// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: pb/document.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Options       *ProcessOptions        `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentRequest) Reset() {
	*x = DocumentRequest{}
	mi := &file_pb_document_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentRequest) ProtoMessage() {}

func (x *DocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_document_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentRequest.ProtoReflect.Descriptor instead.
func (*DocumentRequest) Descriptor() ([]byte, []int) {
	return file_pb_document_proto_rawDescGZIP(), []int{0}
}

func (x *DocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *DocumentRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *DocumentRequest) GetOptions() *ProcessOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ProcessOptions struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	EnableOcr              bool                   `protobuf:"varint,1,opt,name=enable_ocr,json=enableOcr,proto3" json:"enable_ocr,omitempty"`
	EnableSummarization    bool                   `protobuf:"varint,2,opt,name=enable_summarization,json=enableSummarization,proto3" json:"enable_summarization,omitempty"`
	EnableEntityExtraction bool                   `protobuf:"varint,3,opt,name=enable_entity_extraction,json=enableEntityExtraction,proto3" json:"enable_entity_extraction,omitempty"`
	Language               string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ProcessOptions) Reset() {
	*x = ProcessOptions{}
	mi := &file_pb_document_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessOptions) ProtoMessage() {}

func (x *ProcessOptions) ProtoReflect() protoreflect.Message {
	mi := &file_pb_document_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessOptions.ProtoReflect.Descriptor instead.
func (*ProcessOptions) Descriptor() ([]byte, []int) {
	return file_pb_document_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessOptions) GetEnableOcr() bool {
	if x != nil {
		return x.EnableOcr
	}
	return false
}

func (x *ProcessOptions) GetEnableSummarization() bool {
	if x != nil {
		return x.EnableSummarization
	}
	return false
}

func (x *ProcessOptions) GetEnableEntityExtraction() bool {
	if x != nil {
		return x.EnableEntityExtraction
	}
	return false
}

func (x *ProcessOptions) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type DocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	ExtractedText string                 `protobuf:"bytes,2,opt,name=extracted_text,json=extractedText,proto3" json:"extracted_text,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Entities      []*Entity              `protobuf:"bytes,4,rep,name=entities,proto3" json:"entities,omitempty"`
	Metadata      *DocumentMetadata      `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Stats         *ProcessingStats       `protobuf:"bytes,6,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentResponse) Reset() {
	*x = DocumentResponse{}
	mi := &file_pb_document_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentResponse) ProtoMessage() {}

func (x *DocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_document_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentResponse.ProtoReflect.Descriptor instead.
func (*DocumentResponse) Descriptor() ([]byte, []int) {
	return file_pb_document_proto_rawDescGZIP(), []int{2}
}

func (x *DocumentResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentResponse) GetExtractedText() string {
	if x != nil {
		return x.ExtractedText
	}
	return ""
}

func (x *DocumentResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *DocumentResponse) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *DocumentResponse) GetMetadata() *DocumentMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DocumentResponse) GetStats() *ProcessingStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type DocumentChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,3,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	TotalChunks   int32                  `protobuf:"varint,4,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	Options       *ProcessOptions        `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentChunk) Reset() {
	*x = DocumentChunk{}
	mi := &file_pb_document_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentChunk) ProtoMessage() {}

func (x *DocumentChunk) ProtoReflect() protoreflect.Message {
	mi := &file_pb_document_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentChunk.ProtoReflect.Descriptor instead.
func (*DocumentChunk) Descriptor() ([]byte, []int) {
	return file_pb_document_proto_rawDescGZIP(), []int{3}
}

func (x *DocumentChunk) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *DocumentChunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *DocumentChunk) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *DocumentChunk) GetOptions() *ProcessOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type DocumentChunkResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DocumentId      string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	ExtractedText   string                 `protobuf:"bytes,2,opt,name=extracted_text,json=extractedText,proto3" json:"extracted_text,omitempty"`
	ProcessedChunks int32                  `protobuf:"varint,3,opt,name=processed_chunks,json=processedChunks,proto3" json:"processed_chunks,omitempty"`
	IsFinal         bool                   `protobuf:"varint,4,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	Stats           *ProcessingStats       `protobuf:"bytes,5,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DocumentChunkResponse) Reset() {
	*x = DocumentChunkResponse{}
	mi := &file_pb_document_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentChunkResponse) ProtoMessage() {}

func (x *DocumentChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_document_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentChunkResponse.ProtoReflect.Descriptor instead.
func (*DocumentChunkResponse) Descriptor() ([]byte, []int) {
	return file_pb_document_proto_rawDescGZIP(), []int{4}
}

func (x *DocumentChunkResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentChunkResponse) GetExtractedText() string {
	if x != nil {
		return x.ExtractedText
	}
	return ""
}

func (x *DocumentChunkResponse) GetProcessedChunks() int32 {
	if x != nil {
		return x.ProcessedChunks
	}
	return 0
}

func (x *DocumentChunkResponse) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *DocumentChunkResponse) GetStats() *ProcessingStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type EntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	EntityTypes   []string               `protobuf:"bytes,3,rep,name=entity_types,json=entityTypes,proto3" json:"entity_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityRequest) Reset() {
	*x = EntityRequest{}
	mi := &file_pb_document_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityRequest) ProtoMessage() {}

func (x *EntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_document_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityRequest.ProtoReflect.Descriptor instead.
func (*EntityRequest) Descriptor() ([]byte, []int) {
	return file_pb_document_proto_rawDescGZIP(), []int{5}
}

func (x *EntityRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *EntityRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *EntityRequest) GetEntityTypes() []string {
	if x != nil {
		return x.EntityTypes
	}
	return nil
}

type EntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Entities      []*Entity              `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityResponse) Reset() {
	*x = EntityResponse{}
	mi := &file_pb_document_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityResponse) ProtoMessage() {}

func (x *EntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_document_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityResponse.ProtoReflect.Descriptor instead.
func (*EntityResponse) Descriptor() ([]byte, []int) {
	return file_pb_document_proto_rawDescGZIP(), []int{6}
}

func (x *EntityResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *EntityResponse) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Confidence    float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	StartOffset   string                 `protobuf:"bytes,4,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	EndOffset     string                 `protobuf:"bytes,5,opt,name=end_offset,json=endOffset,proto3" json:"end_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_pb_document_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_pb_document_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_pb_document_proto_rawDescGZIP(), []int{7}
}

func (x *Entity) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Entity) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Entity) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Entity) GetStartOffset() string {
	if x != nil {
		return x.StartOffset
	}
	return ""
}

func (x *Entity) GetEndOffset() string {
	if x != nil {
		return x.EndOffset
	}
	return ""
}

type DocumentMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PageCount        int32                  `protobuf:"varint,1,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`
	DetectedLanguage string                 `protobuf:"bytes,2,opt,name=detected_language,json=detectedLanguage,proto3" json:"detected_language,omitempty"`
	DocumentType     string                 `protobuf:"bytes,3,opt,name=document_type,json=documentType,proto3" json:"document_type,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DocumentMetadata) Reset() {
	*x = DocumentMetadata{}
	mi := &file_pb_document_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentMetadata) ProtoMessage() {}

func (x *DocumentMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pb_document_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentMetadata.ProtoReflect.Descriptor instead.
func (*DocumentMetadata) Descriptor() ([]byte, []int) {
	return file_pb_document_proto_rawDescGZIP(), []int{8}
}

func (x *DocumentMetadata) GetPageCount() int32 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

func (x *DocumentMetadata) GetDetectedLanguage() string {
	if x != nil {
		return x.DetectedLanguage
	}
	return ""
}

func (x *DocumentMetadata) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

type ProcessingStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProcessingTimeMs int64                  `protobuf:"varint,1,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	TextLength       int32                  `protobuf:"varint,2,opt,name=text_length,json=textLength,proto3" json:"text_length,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProcessingStats) Reset() {
	*x = ProcessingStats{}
	mi := &file_pb_document_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingStats) ProtoMessage() {}

func (x *ProcessingStats) ProtoReflect() protoreflect.Message {
	mi := &file_pb_document_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingStats.ProtoReflect.Descriptor instead.
func (*ProcessingStats) Descriptor() ([]byte, []int) {
	return file_pb_document_proto_rawDescGZIP(), []int{9}
}

func (x *ProcessingStats) GetProcessingTimeMs() int64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

func (x *ProcessingStats) GetTextLength() int32 {
	if x != nil {
		return x.TextLength
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_pb_document_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_document_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_pb_document_proto_rawDescGZIP(), []int{10}
}

type HealthResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Healthy        bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ActiveRequests int32                  `protobuf:"varint,3,opt,name=active_requests,json=activeRequests,proto3" json:"active_requests,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_pb_document_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_document_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_pb_document_proto_rawDescGZIP(), []int{11}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetActiveRequests() int32 {
	if x != nil {
		return x.ActiveRequests
	}
	return 0
}

var File_pb_document_proto protoreflect.FileDescriptor

const file_pb_document_proto_rawDesc = "" +
	"\n" +
	"\x11pb/document.proto\x12\x02pb\"\x97\x01\n" +
	"\x0fDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12,\n" +
	"\aoptions\x18\x04 \x01(\v2\x12.pb.ProcessOptionsR\aoptions\"\xb8\x01\n" +
	"\x0eProcessOptions\x12\x1d\n" +
	"\n" +
	"enable_ocr\x18\x01 \x01(\bR\tenableOcr\x121\n" +
	"\x14enable_summarization\x18\x02 \x01(\bR\x13enableSummarization\x128\n" +
	"\x18enable_entity_extraction\x18\x03 \x01(\bR\x16enableEntityExtraction\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\"\xf9\x01\n" +
	"\x10DocumentResponse\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12%\n" +
	"\x0eextracted_text\x18\x02 \x01(\tR\rextractedText\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12&\n" +
	"\bentities\x18\x04 \x03(\v2\n" +
	".pb.EntityR\bentities\x120\n" +
	"\bmetadata\x18\x05 \x01(\v2\x14.pb.DocumentMetadataR\bmetadata\x12)\n" +
	"\x05stats\x18\x06 \x01(\v2\x13.pb.ProcessingStatsR\x05stats\"\xbc\x01\n" +
	"\rDocumentChunk\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x1f\n" +
	"\vchunk_index\x18\x03 \x01(\x05R\n" +
	"chunkIndex\x12!\n" +
	"\ftotal_chunks\x18\x04 \x01(\x05R\vtotalChunks\x12,\n" +
	"\aoptions\x18\x05 \x01(\v2\x12.pb.ProcessOptionsR\aoptions\"\xd0\x01\n" +
	"\x15DocumentChunkResponse\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12%\n" +
	"\x0eextracted_text\x18\x02 \x01(\tR\rextractedText\x12)\n" +
	"\x10processed_chunks\x18\x03 \x01(\x05R\x0fprocessedChunks\x12\x19\n" +
	"\bis_final\x18\x04 \x01(\bR\aisFinal\x12)\n" +
	"\x05stats\x18\x05 \x01(\v2\x13.pb.ProcessingStatsR\x05stats\"g\n" +
	"\rEntityRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12!\n" +
	"\fentity_types\x18\x03 \x03(\tR\ventityTypes\"Y\n" +
	"\x0eEntityResponse\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12&\n" +
	"\bentities\x18\x02 \x03(\v2\n" +
	".pb.EntityR\bentities\"\x92\x01\n" +
	"\x06Entity\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12!\n" +
	"\fstart_offset\x18\x04 \x01(\tR\vstartOffset\x12\x1d\n" +
	"\n" +
	"end_offset\x18\x05 \x01(\tR\tendOffset\"\x83\x01\n" +
	"\x10DocumentMetadata\x12\x1d\n" +
	"\n" +
	"page_count\x18\x01 \x01(\x05R\tpageCount\x12+\n" +
	"\x11detected_language\x18\x02 \x01(\tR\x10detectedLanguage\x12#\n" +
	"\rdocument_type\x18\x03 \x01(\tR\fdocumentType\"`\n" +
	"\x0fProcessingStats\x12,\n" +
	"\x12processing_time_ms\x18\x01 \x01(\x03R\x10processingTimeMs\x12\x1f\n" +
	"\vtext_length\x18\x02 \x01(\x05R\n" +
	"textLength\"\x0f\n" +
	"\rHealthRequest\"k\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12'\n" +
	"\x0factive_requests\x18\x03 \x01(\x05R\x0eactiveRequests2\x85\x02\n" +
	"\x0fDocumentService\x12<\n" +
	"\x0fProcessDocument\x12\x13.pb.DocumentRequest\x1a\x14.pb.DocumentResponse\x12I\n" +
	"\x15StreamProcessDocument\x12\x11.pb.DocumentChunk\x1a\x19.pb.DocumentChunkResponse(\x010\x01\x128\n" +
	"\x0fExtractEntities\x12\x11.pb.EntityRequest\x1a\x12.pb.EntityResponse\x12/\n" +
	"\x06Health\x12\x11.pb.HealthRequest\x1a\x12.pb.HealthResponseB\rZ\vepublic8/pbb\x06proto3"

var (
	file_pb_document_proto_rawDescOnce sync.Once
	file_pb_document_proto_rawDescData []byte
)

func file_pb_document_proto_rawDescGZIP() []byte {
	file_pb_document_proto_rawDescOnce.Do(func() {
		file_pb_document_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_document_proto_rawDesc), len(file_pb_document_proto_rawDesc)))
	})
	return file_pb_document_proto_rawDescData
}

var file_pb_document_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pb_document_proto_goTypes = []any{
	(*DocumentRequest)(nil),       // 0: pb.DocumentRequest
	(*ProcessOptions)(nil),        // 1: pb.ProcessOptions
	(*DocumentResponse)(nil),      // 2: pb.DocumentResponse
	(*DocumentChunk)(nil),         // 3: pb.DocumentChunk
	(*DocumentChunkResponse)(nil), // 4: pb.DocumentChunkResponse
	(*EntityRequest)(nil),         // 5: pb.EntityRequest
	(*EntityResponse)(nil),        // 6: pb.EntityResponse
	(*Entity)(nil),                // 7: pb.Entity
	(*DocumentMetadata)(nil),      // 8: pb.DocumentMetadata
	(*ProcessingStats)(nil),       // 9: pb.ProcessingStats
	(*HealthRequest)(nil),         // 10: pb.HealthRequest
	(*HealthResponse)(nil),        // 11: pb.HealthResponse
}
var file_pb_document_proto_depIdxs = []int32{
	1,  // 0: pb.DocumentRequest.options:type_name -> pb.ProcessOptions
	7,  // 1: pb.DocumentResponse.entities:type_name -> pb.Entity
	8,  // 2: pb.DocumentResponse.metadata:type_name -> pb.DocumentMetadata
	9,  // 3: pb.DocumentResponse.stats:type_name -> pb.ProcessingStats
	1,  // 4: pb.DocumentChunk.options:type_name -> pb.ProcessOptions
	9,  // 5: pb.DocumentChunkResponse.stats:type_name -> pb.ProcessingStats
	7,  // 6: pb.EntityResponse.entities:type_name -> pb.Entity
	0,  // 7: pb.DocumentService.ProcessDocument:input_type -> pb.DocumentRequest
	3,  // 8: pb.DocumentService.StreamProcessDocument:input_type -> pb.DocumentChunk
	5,  // 9: pb.DocumentService.ExtractEntities:input_type -> pb.EntityRequest
	10, // 10: pb.DocumentService.Health:input_type -> pb.HealthRequest
	2,  // 11: pb.DocumentService.ProcessDocument:output_type -> pb.DocumentResponse
	4,  // 12: pb.DocumentService.StreamProcessDocument:output_type -> pb.DocumentChunkResponse
	6,  // 13: pb.DocumentService.ExtractEntities:output_type -> pb.EntityResponse
	11, // 14: pb.DocumentService.Health:output_type -> pb.HealthResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pb_document_proto_init() }
func file_pb_document_proto_init() {
	if File_pb_document_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_document_proto_rawDesc), len(file_pb_document_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_document_proto_goTypes,
		DependencyIndexes: file_pb_document_proto_depIdxs,
		MessageInfos:      file_pb_document_proto_msgTypes,
	}.Build()
	File_pb_document_proto = out.File
	file_pb_document_proto_goTypes = nil
	file_pb_document_proto_depIdxs = nil
}
